### ISSUE TITLE
Ruby version + yarn

### ISSUE THREAD

**Issue by claudioduarte** [AmilMasic/petstagram#1]
Hi there, Amil! 😄 **First of all, great app**. Your story on Medium was suggested this morning and just had to clone your repo to try it out for myself.

I only wanted to mention that I had to change the Ruby version to **2.7.1** (because it's the default one I use) and run **yarn** to get the app up and running.

On the note, I would suggest adding Ruby 2.6.1 as a pre-requirement and yarn as a step to launch.

**Comment by AmilMasic** [comment]
You needed yarn to launch it? What did it exactly ask? I will add a note that it was built with 2.6.1. 
Thank you

**Comment by claudioduarte** [comment]
I don't recall the exact message but before I launched it, it asked to yarn to run. It's probably because of how I have my environment setup. Don't worry about it.
